# Generated by Django 5.2 on 2025-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finly_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(help_text='Use the first day of the month, e.g. 2025-04-01'),
        ),
    ]
